name: PR Coverage Report

# Define the Python version for coverage reporting at the workflow level
env:
  COVERAGE_PYTHON_VERSION: '3.12'

on:
  pull_request:
    branches: [ main ]

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    # Add permissions needed for PR comments
    permissions:
      contents: read
      pull-requests: write
      actions: read  # Needed to download artifacts
    
    steps:
    - uses: actions/checkout@v4
    
    # Wait for CI workflow to complete and upload artifacts
    - name: Wait for CI workflow
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        check-name: test (${{ env.COVERAGE_PYTHON_VERSION }})  # Wait for the Python 3.12 matrix job
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
    
    # Download coverage artifacts from CI workflow
    - name: Download coverage XML
      uses: actions/download-artifact@v4
      with:
        name: coverage-xml
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        format: markdown
        indicators: true
        output: both
        thresholds: '60 80'
        
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
